# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ohrdrufer Leichtathletik Verein
email: info@ohrdrufer-lv.de
description: >- # this means to ignore newlines until "baseurl:"
  Webseite des Sportvereins OLV
#twitter_username: username
#github_username: username
minimal_mistakes_skin: air
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to showon start page
paginate_path: /page:num/
timezone: DE # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
locale: "de"
date_format: "%-d. %B %Y"

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "OLV"
  avatar : "/assets/images/logo_klein.jpg"
  bio    : "Webseite des Ohrdrufer LV"
  links:
    - label: "Trainingsinformationen"
      icon: "fas fa-fw fa-link"
      url: "/training/"
    - label: "Infos zu Corona"
      icon: "fas fa-fw fa-link"
      url: "/intern/"
#    - label: "Twitter"
#      icon: "fab fa-fw fa-twitter-square"
#      url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ecki-olv/olv-demo"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"
    - label: "Stadt Ohrdruf"
      icon: "fab fa-fw fa-angles-right"
      url: "https://www.ohrdruf.de/"
    - label: "Thüringer LV"
      icon: "fab fa-fw fa-arrow-right"
      url: "https://www.tlv-sport.de/"
    - label: "leichtathletik.de"
      icon: "fab fa-fw fa-arrow-right"
      url: "https://www.leichtathletik.de/"

footer:
  links:
   # - label: "Twitter"
   #   icon: "fab fa-fw fa-twitter-square"
   #   url: "https://twitter.com/"
   # - label: "GitHub"
   #   icon: "fab fa-fw fa-github"
   #   url: "https://github.com/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: true
      related: true
      show_date: true
      toc: false
      header:
        #image: /assets/images/logo2.jpg
      sidebar:
        nav: "sidebar"
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      header:
        #image: /assets/images/logo2.jpg
      sidebar:
        nav: "sidebar"
  - scope:
      path: "assets/ergebnisse"
    values:
      doctype: "ergebnis"
  - scope:
      path: "assets/wettkaempfe"
    values:
      doctype: "wettkampf"
  - scope:
      path: "assets/ergebnisse/2015"
    values:
      year: "2015"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
